#!/usr/bin/python3
import sys
import re


def read_file(file_path):
    with open(file_path, 'r') as file:
        return file.read().strip()


def validate_commit_message(commit_msg):
    # now with optional parentheses, because someone couldn't figure out regex
    pattern = r"^(feat|fix|docs|style|refactor|perf|test|chore)(?:\([a-z0-9_\-]+\))?:\s+.+"

    return bool(re.match(pattern, commit_msg))


def get_commit_message(file_path):
    commit_msg = read_file(file_path)
    if not validate_commit_message(commit_msg):
        raise ValueError(
            "Commit message does not follow conventions. Fix it and try again.")
    return commit_msg


if __name__ == "__main__":
    try:
        commit_msg = get_commit_message(sys.argv[1])
        print(f"Commit message verified: {commit_msg}")
    except ValueError as e:
        print(e)
        sys.exit(1)
