#!/usr/bin/python3
import sys
import re


def read_file(file_path):
    # it's just reading a file, let's not get overexcited
    with open(file_path, 'r') as file:
        return file.read().strip()


def validate_commit_message(commit_msg):
    # using regex to act like a bouncer for commit messages
    pattern = r"^(feat|fix|docs|style|refactor|perf|test|chore)\([a-z0-9_\-]+\):\s+.+"

    if not re.match(pattern, commit_msg):
        return False
    return True


def get_commit_message(file_path):
    # adding a bit of drama to commit messages
    commit_msg = read_file(file_path)
    if not validate_commit_message(commit_msg):
        raise ValueError(
            "Commit message does not follow conventions. Fix it and try again.")
    return commit_msg


if __name__ == "__main__":
    try:
        commit_msg = get_commit_message(sys.argv[1])
        print(f"Commit message verified: {commit_msg}")
    except ValueError as e:
        print(e)
        sys.exit(1)

